config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  root 'dashboard#index'

  
  resources :dashboard
  get 'dadmin' => 'dashboard#dadmin'
  get 'myorders' => 'dashboard#myorders'
  get 'label' => 'dashboard#label'
  resources "contacts", only: [:new, :create]

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  resources "orders"
  get "/confirm" => "confirmations#show"
  get 'dconfirmation' => 'orders#confirmation'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "jacksharville@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  belongs_to :user
  scope :not_completed_orders, -> {
    where(:complete => false)
  }

  include MailForm::Delivery

  # append :remote_ip, :user_agent, :session
  # attributes :name, :email, :created_at

  def headers
    {
      :to => "ops@dms-intl.com",
      :from => "ops@dms-intl.com",
      :subject => "A new order has been placed on the DMS website."
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ActiveAdmin.register User do
    permit_params(:name, :email, :password_digest, :remember_token)
  end
  after_create

  def password_required?
    new_record? ? false : super
  end
  
  has_many :orders
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable , :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :address_line_1, :address_line_2, :postcode, :city, :country) }
      end

      def verify_is_admin
        (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
      end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :authenticate_user!
 
  def index
  end

  def admindashboard
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
  
  def adminuser
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
  
  def dadmin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    @order = Order.order("name").page(params[:page]).per(1)
  end
  
  def myorders
    @order = current_user.orders.order("name").page(params[:page]).per(1)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def label
    @order = current_user.orders.order("name").page(params[:page]).per(1)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
    @order.email = current_user.email
    @order.name = current_user.name
    @order.address_line_1 = current_user.address_line_1
    @order.address_line_2 = current_user.address_line_2
    @order.postcode = current_user.postcode
    @order.city = current_user.city
    @order.country = current_user.country
    if @order.save
      redirect_to dconfirmation_path
    end
  end

  def order_params
    params.require(:order).
      permit(
        :pieces,
        :email,
        :delivery_name,
        :company_name,
        :delivery_address1,
        :delivery_address2,
        :delivery_address3,
        :delivery_city,
        :delivery_postcode,
        :delivery_country,
        :phone,
        :package_contents,
        :description_content,
        :restricted_items,
        :terms_conditions,
        :insurance,
        :contents_value,
        :cf_reference,
        :reference_number,
        :service
        )
  end
  def show
    @user = User.find(params[:id])
  end

  def confirmation
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def why
  end

  def trak
  end
  
  def contact
  end
  
  def mydms
  end
  
  def air
  end
  
  def ocean
  end
  
  def road
  end
  
  def courier
  end
  
  def fulfilment
  end
  
  def express
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/contacts/create.html.haml
.container
 %h1 We appreciate your contact. We have received it and will respond directly to your email or phone.

app/views/contacts/new.html.haml
.container
  .col-md-4
    %h1 DMS International Ltd.
 
    .text-norm
    %p
      London Heathrow: +44 (0)20 8897 1766
      Suite 207, UCH House, Old Bath Road, Colnbrook, Berkshire SL3 0NW
    %p
      London Gatwick: +44 (0)1293 772608
      Unit 1, Bridge Industrial Estate, Balcombe Road, Horley, Surrey RH6 9HU
  
  .col-md-8
    .contactform
      %h1 Contact Us
      = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
        %br
        = f.input :name, :required => true
        = f.input :email, :required => true
        = f.input :phone, :required => false
        = f.input :message, :as => :text, :required => false, :input_html => {:rows => 10}

        .hidden
          = f.input :nickname, :hint => 'Leave this field blank!'
        .form-actions
          = f.button :submit, 'Send message', :class=> "btn btn-primary"

app/views/dashboard/_navbard.html.haml
%ul.nav.nav-pills.nav-stacked
  %li.active
    = link_to "My account"
  = if current_user.admin? then
    - link_to "Admin Dashboard", dadmin_path, :class => 'btn btn-danger'
  - else
  %li
    = link_to "Edit My Account", edit_user_registration_path
  %li
    = link_to "My Placed Orders", myorders_path
  %li
    = link_to "Place New Order", new_order_path

app/views/dashboard/dadmin.html.haml
.col-md-12
  .admindash
    %h1 Admin Dashboard
    .text-norm
      Welcome to the admin dashboard here you can see incoming and outgoing orders.
.row.col-md-12
  .col-md-8
    - for order in @order
      %h2
        = order.user.name if order.user
      .orderpanel
        .clientarea
          Client name:
          = order.user.name if order.user
          %br
          Client email:
          = order.user.email if order.user
          %br
          Client address ... -->:
          %br
          = order.user.address_line_1 if order.user
          %br
          = order.user.address_line_2 if order.user
          %br
          = order.user.postcode if order.user
          %br
          = order.user.city if order.user
          %br
          = order.user.country if order.user
        .delivarea
          delivery_name:
          = order.delivery_name
          %br
          company_name:
          = order.company_name
          %br
          delivery_address1:
          = order.delivery_address1
          %br
          delivery_address2:
          = order.delivery_address2
          %br
          delivery_address3:
          = order.delivery_address3
          %br
          delivery_city:
          = order.delivery_city
          %br
          delivery_postcode:
          = order.delivery_postcode
          %br
          phone:
          = order.phone
          %br
          package_contents:
          = order.package_contents
          %br
          description_content:
          = order.description_content
          %br
          contents_value:
          = order.contents_value
          %br
          cf_reference:
          = order.id
          CR
          %br
          service level:
          = order.service
          %br
          reference_number:
          = order.reference_number
        .tac
          restricted_items:
          = order.restricted_items
          %br
          terms_conditions:
          = order.terms_conditions
          %br
          insurance:
          = order.insurance
          = order.id
  .col-md-4.sidebar
    = paginate @order
    %p
    = link_to "Data Control", admin_dashboard_path, :class => 'btn-danger btn'
    %p
    = link_to "Back to Dashboard", :back, :class => 'btn-danger btn'

app/views/dashboard/index.html.haml
.col-md-2
  =render 'navbard'
.col-md-10
  %h1 
    Welcome to your Dashboard
    / = current_user.name + '.'
  .text-norm.contactform.col-md-10
    %u
      %h2 Your current details are :
      %p
    %h2 Email:

    = current_user.email

    %h2 Full Name:

    = current_user.name

    %h2 Address Line 1:

    = current_user.address_line_1

    %h2 Address Line 2:

    = current_user.address_line_2

    %h2 Postcode:

    = current_user.postcode

    %h2 City:

    = current_user.city

    %h2 Country:

    = current_user.country
    %p
    %u
      %font{:color => "red"} *If any of the fields are blank/wrong please fill them in in 
      = link_to "Edit My Account", edit_user_registration_path
      

app/views/dashboard/label.html.haml
%h1 labels
- for order in @order
= paginate @order
  .labeley
    .label-title
      %h2 DMS international
    .label-cr.pull-right
      = order.id
      CR
    .label-client
      %h5 Client Details:
      Client name:
      = order.user.name
      %br
      Client email:
      = order.user.email
      %br
      Client address:
      = order.user.address_line_1
      ,
      = order.user.address_line_2
      %br
      = order.user.postcode
      %br
      = order.user.city
      %br
      = order.user.country
    .label-del
      %h5 Delivery Details:
      Delivery name:
      = order.delivery_name
      %br
      Delivery address:
      = order.delivery_address1
      = order.delivery_address2
      = order.delivery_address3
      %br
      = order.delivery_city
      %br
      = order.delivery_postcode
      %br
      service level:
      = order.service
      %br
    -if !order.pieces.nil?
      .pull-right.label-pc
        __ /
        = order.pieces
        Pieces
  = link_to_next_page @order, 'Next Page'
%br
%button.btn.btn-primary{:href => "#", :onclick => "window.print();return false;"} print me

app/views/dashboard/myorders.html.haml
.col-md-12
  %h1 My orders.
  .text-norm
    They are displayed from oldest to newest. If you wish to cancel a order please contact DMS on ops@dms-intl.com or call 01293 772608.
.col-md-8
  - for order in @order
    %h2
      = order.user.name
    .orderpanel
      .clientarea
        Client name:
        = order.user.name
        %br
        Client email:
        = order.user.email
        %br
        Client address ... -->:
        %br
        = order.user.address_line_1
        %br
        = order.user.address_line_2
        %br
        = order.user.postcode
        %br
        = order.user.city
        %br
        = order.user.country
      .delivarea
        delivery_name:
        = order.delivery_name
        %br
        company_name:
        = order.company_name
        %br
        delivery_address1:
        = order.delivery_address1
        %br
        delivery_address2:
        = order.delivery_address2
        %br
        delivery_address3:
        = order.delivery_address3
        %br
        delivery_city:
        = order.delivery_city
        %br
        delivery_postcode:
        = order.delivery_postcode
        %br
        phone:
        = order.phone
        %br
        package_contents:
        = order.package_contents
        %br
        description_content:
        = order.description_content
        %br
        contents_value:
        = order.contents_value
        %br
        cf_reference:
        = order.id
        CR
        %br
        service level:
        = order.service
        %br
        reference_number:
        = order.reference_number
      .tac
        restricted_items:
        = order.restricted_items
        %br
        terms_conditions:
        = order.terms_conditions
        %br
        insurance:
        = order.insurance
.col-md-4
  .sidebar
    = paginate @order
    = link_to "Print Labels", label_path, :class => 'btn btn-primary'

app/views/home/_footer.html.haml
#footer
.footer
  %hr
  .contactnum.col-md-3
    London Heathrow:  +44 (0)20 8897 1766
    %p London Gatwick:  +44 (0)1293 772608
  .push-right
    = image_tag('otherlogos3.gif', :class => "logo3")

app/views/home/_navbar.html.haml
.col-lg-12
  %nav.navbar.navbar-default
    .container-fluid
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/"} DMS
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            %a{:href => "http://dms-intl.com/"} Back To Main Site
          %li
            .logged
              - if user_signed_in?
                #{current_user.email} Not you ? #{link_to 'Sign out', destroy_user_session_path, :method => :delete}
              - else
                #{link_to 'sign in', new_user_session_path}

app/views/home/index.html.haml
.row
  .col-lg-12
    =image_tag('services_montage1.jpg', :class => 'col-md-4 montage1')
    .col-md-8
      //Home page text
      .text-title
        %h1 DMS International Freight and Courier Services

      .text-norm
        %p DMS International Limited is a privately-owned, worldwide logistics provider. Established in 1967, we have built an industry-wide reputation for expertise, reliability and integrity. We offer a tailored service across a multitude of markets to include warehousing, fulfilment, distribution, transport and complete supply chain management that is specific to individual customer requirements and designed to achieve the highest standard of efficiency, quality and value.

        %p Our modern facilities are located at key UK locations at Heathrow and Gatwick Airports, supported by a global network of agents representing us as partners we are committed in taking our company and clientele forward by providing an exhaustive range of cargo management solutions for the ever-changing world. DMS offer multiple industry/product experience and our philosophy is to create business partnerships with our customers providing dedicated staff and one point of contact and control.

        %p Our proactive approach and expertise enables us to take responsibility for the management of all logistics activities on behalf of our customers, which affords us an unrivalled reputation for providing the most efficient consumer direct service through our tailored warehouse management system. Our reputation has been built working alongside some of the most well know high profile companies, delivering stock around the World to their stores and replenishing any requirement they have via our own fleet of vehicles or selected partners.
        %p We are friendly team, totally professional, with  a no-nonsense approach, and we always deliver.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    %title DMS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %header
      .container
        /Nav Bar and Banner
        = image_tag('banner.jpg', :class => "banner img-responsive")
        =render '/home/navbar'
        /alerts
        / %p.notice= notice
        / %p.alert= alert

        /contact alert
        .col-lg-12
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                %a.close{"data-dismiss" => "alert"}
                  &times;
                = content_tag :div, msg, :id => "flash_#{name}"

    %p
    %body
      .container
        = yield
    %footer
      .container
        =render '/home/footer'

app/views/orders/confirmation.html.haml
.col-lg-12
  %h2 Thank you
  .text-norm
    Your consignment will be scheduled for collection. If you have any questions please email ops@dms-intl.com or call 01293 772608.
    / %br
    / [Log Out] This will take the customer to the DMS website home page.
    %br
    %br
    = link_to "Print Labels", label_path, :class => 'btn btn-primary'
    %br
    %br 
    = link_to "Place another order", new_order_path, :class => 'btn btn-primary'

app/views/orders/create.html.haml
.container

app/views/orders/new.html.haml
.col-lg-12
  %h1 DMS INTERNATIONAL - CUSTOMER PORTAL & PACKAGE BOOKING PAGE
  .text-norm.col-md-8
    %p
      Please use the form below to enter details of your package/s.
    %p
      If you have any questions please call us on 01293 772608.
    %p
      Use this form to order packages no larger than 175cm square and no heavier than 31Kg.
      If your package/s are larger or heavier than this please call us on 01293 772608.
/ .col-md-3.pull-right
/   %h2 Quick Navigation
/   %ul.nav.nav-pills.nav-stacked
/     %li.active{:role => "presentation"}
/       %a{:href => "Collection"} Collection
/     %li{:role => "presentation"}
/       %a{:href => "Delivery"} Delivery
/     %li{:role => "presentation"}
/       %a{:href => "Contence"} Contence


.col-md-8
  .panel.panel-default
    .panel-heading
      %h3.panel-title Collection Address:
      %span.pull-right.clickable.panel-collapsed
        %i.glyphicon.glyphicon-chevron-down
    .panel-body.panel-collapsed{:style => "display: none;"}
      %h2
        Welcome,
        = current_user.name
        These are your current details.
        %p
        %font{:color => "red"} *If any of the fields are blank/wrong please fill them in in 
        = link_to "Edit My Account", edit_user_registration_path
        %p
      %h2 Email:

      = current_user.email

      %h2 Full Name:

      = current_user.name

      %h2 Address Line 1:

      = current_user.address_line_1

      %h2 Address Line 2:

      = current_user.address_line_2

      %h2 Postcode:

      = current_user.postcode

      %h2 City:

      = current_user.city

      %h2 Country:

      = current_user.country
      %p



.col-md-8
  .panel.panel-default
    .panel-heading
      %h3.panel-title Delivery Address:
      %span.pull-right.clickable
        %i.glyphicon.glyphicon-chevron-up
    .panel-body
      %h2 To place a new order we require some additional information please fill that in below:
      = simple_form_for @order do |f|
        = f.input :delivery_name, :label => 'Delivery recipient full name', :required => true
        %p
        = f.input :company_name
        %p 
        = f.input :delivery_address1, :input_html => { :id => "first_line" }, :label => 'Address line 1', :required => true
        %p
        = f.input :delivery_address2, :input_html => { :id => "second_line" }, :label => 'Address line 2'
        %p
        = f.input :delivery_address3, :input_html => { :id => "third_line" }, :label => 'Address line 3'
        %p
        = f.input :delivery_city, :input_html => { :id => "post_town" }, :label => 'City', :required => true
        %p
        = f.input :delivery_postcode, :input_html => { :id => "postcode" }, :label => 'postcode', :required => true, :placeholder => 'Don’t enter postcode here if you intend to use find my address.'
        %p
        #postcode_lookup_field
        :javascript
          $('#postcode_lookup_field').setupPostcodeLookup({
              // Set your API key
              api_key: 'ak_idks8a8h7ZGzRUWMOngHE5c7SBLhC',
              // Pass in CSS selectors pointing to your input fields to pipe the results
              output_fields: {
                  line_1: '#first_line',  
                  line_2: '#second_line',         
                  line_3: '#third_line',
                  post_town: '#post_town',
                  postcode: '#postcode'
              },
              button_class: 'btn-primary btn',
              input_class: 'postcode'
          });
        %p
        = f.input :phone, :label => 'Contact/phone number', :required => true, :limit => 12
        %p
        = f.select :pieces, options_for_select(0..20), { prompt: "Number Of Pieces" }, :required => true
        %p
        = f.input :description_content, :label => 'Description of contents.'
        %br
        = f.input :restricted_items, :label => 'I have read and agree to the restricted item list.', :required => true, :input_html => { :checked => true }
        %br
        = f.input :terms_conditions, :label => 'I agree to the T&C.', :class => 'checkbox', :required => true, :input_html => { :checked => true }
        %br
        = f.input :insurance, :label => 'If in need of insurance tick this box'
        %br
        = f.input :contents_value, :label => 'Estimated value', :limit => 12, :hint => "Should be in Pounds."
        %p
        / = f.input :cf_reference, :label => 'Consignment reference', :hint => 'This will be automatically entered'
        %p
        = f.input :service, :label => 'Service Level', :required => true, :as => :select, :collection => [['DMS Express', 'DMS Express'], ['DMS 09.00', 'DMS 09.00'], ['DMS 10.00', 'DMS 10.00'], ['DMS 12.00', 'DMS 12.00']]
        %p
        = f.input :reference_number
        %p
        = f.button :submit, :class => 'btn-primary'

:css
  .panel-heading span {
      margin-top: -20px;
      font-size: 15px;
  }
  .row {
      margin-top: 40px;
      padding: 0 10px;
  }
  .clickable {
      cursor: pointer;
  }
:javascript
  jQuery(function ($) {
      $('.panel-heading span.clickable').on("click", function (e) {
          if ($(this).hasClass('panel-collapsed')) {
              // expand the panel
              $(this).parents('.panel').find('.panel-body').slideDown();
              $(this).removeClass('panel-collapsed');
              $(this).find('i').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
          }
          else {
              // collapse the panel
              $(this).parents('.panel').find('.panel-body').slideUp();
              $(this).addClass('panel-collapsed');
              $(this).find('i').removeClass('glyphicon-chevron-up').addClass('glyphicon-chevron-down');
          }
      });
  });

app/views/pages/air.html.haml
.row
  .col-lg-12
    =image_tag('air-freight-montage.jpg', :class => 'col-md-4')
    .col-md-8
      //Home page text
      .text-title
        %h1 Air Freight Services

      .text-norm
        With our offices located at London’s Heathrow & Gatwick Airports, DMS are ideally situated to provide worldwide Export and Import Air Freight Services. Our vast experience and extensive knowledge of global markets combined with the latest technology will help expedite the handling of your import and export shipments.
        %p 
        Our Air Freight Services include:
        %p
        %ul.col-md-4
          %li Track and Trace
          %p
          %li Project Cargo
          %p
          %li Airline Direct Shipments
          %p
          %li Daily Consolidation
          %p
          %li Charters
          %p
          %li Door to Door
          %p
          %li Worldwide Courier
        %ul.col-md-4
          %li Insurance
          %p
          %li Customs Clearance
          %p
          %li Consular Work
          %p
          %li Letters of Credit
          %p
          %li Cross Trade
          %p
          %li Cargo Assembly
          %p
          %li Packing
      .coverage.col-md-8
        %h2 COVERAGE 24/7/365

        

app/views/pages/courier.html.haml
.row
  .col-lg-12
    =image_tag('courier-montage.jpg', :class => 'col-md-4')
    .col-md-8
      //Home page text
      .text-title
        %h1 DMS Courier Services

      .text-norm
        If you are looking for a company that you can trust with your important shipments then place your confidence in DMS International Courier Services.

        %p At DMS due to our massive buying power with the biggest courier companies in the world we can offer the very best courier rates and world class service at a fraction of the normal cost.

        %p DMS track all your parcels for you through our bespoke D-Trax system and give you live up dates via email so rest assured that if you don’t have the time to track your shipments we will be doing it for you

        %p We offer a free collection service from a UK address that is convenient for you

        %p DMS International has nearly 50 years’ experience in global shipping. With our expertise and the partners we can deal with any parcel you need to send.

app/views/pages/express.html.haml
.row
  .col-lg-12
    =image_tag('time_montage.jpg', :class => 'col-md-4')
    .col-md-8
      //Home page text
      .text-title
        %h1 DMS Express Time Critical Deliveries

      .text-norm
        DMS International Time Critical services operate globally, including emergency van services within the UK and mainland Europe, and express worldwide air services, providing immediate door-to-door solutions to the most challenging deadlines.   With the fastest loading times, DMS Express ensures your consignment is on its way and being driven directly to your customers door – direct 24/7/365.

        %p
        Our priority services were honed to support the aviation, automotive and pharmaceutical sectors, so line-stops and AOGs are all part of our daily demands. When scheduled flights aren’t fast enough, or flight shut-offs have been missed, our express direct drive vans and trucks will move those spares that simply cannot wait.

        %p
        DMS International are experienced road logistics specialists and aim to provide the highest quality service to all customers, and our network links all major countries, regions and cities.

        %p 
        Whatever the nature of the load or its degree of urgency, from routine to express, we have a comprehensive range of options that utilise our extensive fleet of state-of-the-art vehicles, each equipped with the latest load security and tracking technology, to ensure customers receive real-time transport management solutions and control.

app/views/pages/fulfilment.html.haml
.row
  .col-lg-12
    =image_tag('road-freight.jpg', :class => 'col-md-4')
    .col-md-8
      //Home page text
      .text-title
        %h1 Fulfilment Services

      .text-norm
        Our fulfilment experts can integrate our warehousing services with distribution and other value added services.

        %p On receipt of your goods our stock team, check the accuracy of the shipment, and ensure all your good have arrived undamaged.

        %p Each item is booked and then placed on our bespoke system, this enables you to check on your items using our 24hour web access. We look after your stock list and give you regular updates.

        %p Every order is packed to ensure your item arrives safely at its destination
        extensive multipurpose warehousing and storage facilities at all of our office locations including extra facilities strategically located worldwide.

        %p Our warehouse facilities are suitably equipped for customers requiring a large buffer, contingency store, transit store, and a facility to warehouse spares or to utilize for fabrication. Cutting edge inventory systems provide us the ability to dispatch urgent items to anywhere in the world.
        %p 
        DMS Fulfilment Services include:
        %p
        %ul.col-md-4
          %li Pick and Pack
          %p
          %li Packaging Services
          %p
          %li Stock Control
          %p
          %li Inventory Management Reports
          %p
          %li Web-based Inventory Tracking
          %p
          %li Bonded Warehouse
        %ul.col-md-4
          %li 24 hour CCTV
          %p
          %li Shipping
          %p
          %li Comercial Invoicing
          %p
          %li Stock Takes
          %p
          %li 24 hour Web Access
      .coverage.col-md-8
        %h2 Reliable Fulfilment Solutions

        

app/views/pages/mydms.html.haml
=image_tag'customer-portal.jpg'
Content login coming soon.

app/views/pages/road.html.haml
.row
  .col-lg-12
    =image_tag('road-freight.jpg', :class => 'col-md-4')
    .col-md-8
      //Home page text
      .text-title
        %h1 Road Freight Services

      .text-norm
        DMS International are experienced road freight and logistics specialists. In combination with an efficient transport network DMS aim to provide the highest quality service to all clients. Our networks link all major cities and regions.

        %p Whatever the nature of the load, we offer a comprehensive range of road transportation services, utilizing our extensive fleet of state-of-the-art vehicles. Our vehicles are equipped with the latest load security and track & trace technology giving live time transport management and control.
        %p 
        DMS Road Freight Services include:
        %p
        %ul.col-md-4
          %li Full and Part-Load Network
          %p
          %li Heavy and Abnormal Loads
          %p
          %li Track & Trace Technology
      .coverage.col-md-8
        %h2 COVERAGE 24/7/365

        